apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - alertmanager:9093

    rule_files:
      - "rules/*.yml"

    scrape_configs:
      - job_name: 'spring-boot-application-k8s'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: my-demo
        metrics_path: /actuator/prometheus
        scrape_interval: 10s
  
      # - job_name: 'spring-boot-application-k8s-2'
      #   static_configs:
      #     - targets: ['my-demo:9000']
      #   metrics_path: /actuator/prometheus

      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter:9100']

      - job_name: 'cadvisor'
        static_configs:
          - targets: ['cadvisor:8080']
        scrape_interval: 10s
